name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release

    - name: Publish artifacts
      run: |
        mkdir publish
        cp -R ghrunner/bin/Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release Artifacts
        path: publish/
